#!/usr/bin/env python

#
#  displayPoints.py
#
#  purpose: visualizes points on the sphere, generated by Spherepoints projects.
#           Essentially facilitates testing of Spherepoints project.
#
#  Copyright @2012 Arvind S. Rao
#  License: GNU
#

import csv, os, argparse
import numpy as np
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt


def parse(num=5):
    parser = argparse.ArgumentParser(description="This program tests the capability of spherepoints by generating and then plotting on S^2")
    parser.add_argument("--num", type=int, help="the number of points to generate on the sphere")
    pargs = parser.parse_args()

    if pargs.num:
        num = pargs.num 

    return num

def main():
    num_points = parse()
    os.system("/Users/arvind/Projects/SpherePoints-build/bin/main " + str(num_points) + " > points.txt")
    reader = csv.reader(open('points.txt', 'rb'))
    a = np.array( [ [float(col) for col in row ] for row in reader ] )
    
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    ax.scatter( a[:,0], a[:,1], a[:,2], c='r')

    ax.set_xlabel('X Label')
    ax.set_ylabel('Y Label')
    ax.set_zlabel('Z Label')
    plt.show()


#-----------------Invoke Main----------------------#    
if __name__ == '__main__':
	main()




